### PR TITLE
Add Ellipse interior/outline image support

### LINKED ISSUE #210: Ellipse interior/outline image support
Add texture and outline stippling capabilities to the Ellipse shape with similar capability and options to Polygon.

Closes #18

### PR DESCRIPTION
**Pull request by zglueck**
### Description of the Change

This change implements interior/outline image support. Implementation borrows heavily from Path/Polygon.

### Why Should This Be In Core?

Unifies interior/outline API with Path/Polygon and provides additional capability for the Ellipse shape.

### Applicable Issues
Closes #210 
Compliments #18

### CODE REVIEW

**Comment by zglueck** [comment]
Closing this while I add texture coordinate matrix utility to AbstractShape.

**Comment by zglueck** [comment]
I've updated this pull request to include the refactored `computeTexCoordMatrix` method added to AbstractShape and shared by Ellipse, Path, and Polygon.

**Comment by zglueck** [comment]
I missed the convention, sorry. What about decoupling "repeating" from the texture transform? Would a "screen constant" or "stipple" mention be better?

Potential Options:
- `computeScreenConstantTexCoordTransform`
- `computeStippleTexCoordTransform`
- `computeScreenScaledTexCoordTransform`

What do you think?

**Comment by pdavidc** [comment]
To me, those names indicate how the method works. The best names indicate what the subject is trying to accomplish.

**Comment by zglueck** [comment]
Ok, I've updated the name and pushed 👍

**Pull request merged**
